# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('idcomment', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=150, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idproduct', models.IntegerField(primary_key=True, serialize=False)),
                ('nameproduct', models.CharField(blank=True, max_length=100, null=True)),
                ('foodvalue', models.CharField(blank=True, max_length=150, null=True)),
                ('energyvalue', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('idtype', models.IntegerField(primary_key=True, serialize=False)),
                ('nametype', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'type_product',
                'managed': False,
            },
        ),
    ]
