# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myasnoysmak', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('idnews', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст новости')),
                ('url_image', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок новости')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False, 'verbose_name': 'Продукты', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='typeproduct',
            options={'managed': False, 'verbose_name': 'Тип продукта', 'verbose_name_plural': 'Тип продукта'},
        ),
    ]
